package secure_txt_file_content_retrieval;


import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

/* PURPOSE: A ResponseMessage object is used as an efficient means of passing both a File and a byte array (the message
 *  digest generated by the Receiver object) between the Receiver object, the MBRC object, and the Sender object. An
 *  instance of the ResponseMessage class has attributes that can contain both of these pieces of information.
 */
public class ResponseMessage {

    /* Properties */

    // Content (in bytes) of outgoing file generated by the Receiver object
    private final File outgoingFile;

    // Message digest generated by Receiver object's generate() method
    private final byte[] messageDigest;


    /* Constructor */
    public ResponseMessage(File file, byte[] md) {

        this.outgoingFile = file;

        this.messageDigest = md;

    }

    /* Methods */

    // Getter method for the outgoingFile attribute's contents
    public byte[] getFileContents() {
        String fileName = this.outgoingFile.getName();
        byte[] fileContents = new byte[0];
        try {
            fileContents = Files.readAllBytes(Paths.get(fileName));
        } catch (IOException e) {
            e.printStackTrace();
        }
        return fileContents;
    }

    // Getter method for the outgoingFile attribute's file name
    public String getFileName() {
        return this.outgoingFile.getName();
    }

    // Getter method for message digest attribute
    public byte[] getMessageDigest() {
        return this.messageDigest;
    }
}
